### ISSUE TITLE
Add proper README

### ISSUE THREAD

**Issue by s-m-i-t-a** [iodevs/elm-history#7]

**Comment by Ishaan28malik** [comment]
hello can i solve this issue ?

**Comment by s-m-i-t-a** [comment]
Hi @Ishaan28malik ,
yes, you can. :)

**Comment by ondrej-tucek** [comment]
Hi @Ishaan28malik 
I'm sorry but we need the readme asap, because we would like to add this package to package.elm-lang.org and use for our next project.
